# Generated by Django 5.1.5 on 2025-01-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garbagereport',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='garbagereport',
            name='longitude',
        ),
        migrations.AddField(
            model_name='garbagereport',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garbagereport',
            name='stage',
            field=models.CharField(choices=[('Reported', 'Reported'), ('Work Started', 'Work Started'), ('Resolved', 'Resolved')], default='Reported', max_length=20),
        ),
        migrations.AddField(
            model_name='garbagereport',
            name='ticket_id',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
