# Generated by Django 5.1.5 on 2025-01-24 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_garbagereport_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbagereport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='garbagereport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='garbage_reports/'),
        ),
        migrations.AlterField(
            model_name='garbagereport',
            name='reported_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='garbagereport',
            name='stage',
            field=models.CharField(blank=True, choices=[('Reported', 'Reported'), ('Work Started', 'Work Started'), ('Resolved', 'Resolved')], default='Reported', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='garbagereport',
            name='ticket_id',
            field=models.CharField(blank=True, default='', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='garbagereport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
