# Generated by Django 5.1.5 on 2025-01-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_garbagereport_case_number_garbagereport_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='IITB', max_length=255)),
                ('coordinates', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='garbagereport',
            name='zone_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
