# Generated by Django 5.1.5 on 2025-01-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_garbagereport_zone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagereport',
            name='zone_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
