# Generated by Django 5.1.5 on 2025-01-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_garbagereport_zone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagereport',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garbagereport',
            name='resolved_image',
            field=models.ImageField(blank=True, null=True, upload_to='garbage_reports/resolved'),
        ),
    ]
