# Generated by Django 5.1.5 on 2025-01-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_garbagereport_comment_garbagereport_resolved_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagereport',
            name='resolved_coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
