# Generated by Django 5.1.5 on 2025-01-25 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.zone'),
        ),
    ]
